development:
  adapter: postgresql
  encoding: unicode
  database: mi_gran_empresa_development
  pool: 5
  username: postgres
  password: 961219
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: mi_gran_empresa_test
  pool: 5
  username: postgres
  password: 961219
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: mi_gran_empresa_db
  pool: 5
  username: mi_gran_empresa_db_user
  password: xVtsPcet8oRYWM8jeINjbsdF4yVQVEap
  host: 917941b5-1011-4530-b454-159a6d5a4509
  port: 5432


no-tls-verify: true
no-icmp: true

